### PR TITLE
Add labels to chessboard

### LINKED ISSUE #23: add labels to the chessboard
Add labels (1,2,3... and a,b,c...) on the chess board

### PR DESCRIPTION
**Pull request by Mohitraut07**
issue: #23 
In this updated Cell component, I calculate the row and column labels based on the square's position and display them as labels on the chessboard. These labels are positioned in the center of each cell, and their appearance can be customized using CSS styles as needed.

### CODE REVIEW

**Comment by Mohitraut07** [comment]
@moonpatel please review the PR.

**Review by moonpatel — CHANGES_REQUESTED** [review]
The following changes are required:
-> only the first column should contain the row label (i.e. 1,2,3,4...)
-> the row label should start from 1 not 0.
-> there is no column label.

**Comment by Mohitraut07** [comment]
@moonpatel is this ok?

**Comment by moonpatel** [comment]
The labels are not visible

**Comment by Mohitraut07** [comment]
will this work?

**Comment by moonpatel** [comment]
> will this work?

The labels are still not visible

**Pull request closed without merging**
